# File: ~/.config/starship-single-line.toml
# Author: Dan Murphy

[character]
vicmd_symbol = "[❮](bold blue)"

[cmd_duration]
disabled = true

[directory]
truncation_length = 3
#read_only = " "

[git_branch]
format = "[$branch]($style) "

[line_break]
disabled = true

#[python]
#symbol = " "

