# ~/.zshrc
# Author: Dan Murphy

# Language and localization settings
export  LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

system_type=$(uname -s)

# macOS-specific settings
if [ "$system_type" = "Darwin" ]; then
    # Tell ls to be colourful
    export CLICOLOR=1
    export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx

    # Tell grep to highlight matches
    export GREP_OPTIONS='--color=auto'

    # Make Homebrew completions available; see
    # <https://docs.brew.sh/Shell-Completion>
    if type brew &>/dev/null; then
      FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH

      autoload -Uz compinit
      compinit
    fi

    # Use Homebrew's gcc
    alias gcc='gcc-10'
    alias g++='g++-10'
fi

