" File: ~/.vim/gvimrc
" Author: Dan Murphy
" **DEPRECATED** Settings moved to vimrc file


" Use option (alt) as meta key
" This option is only available in MacVim GUI
set macmeta

" Font for GUI Vim
set guifont=Fira\ Code:h14

