# ~/.config/starship.toml
# Author: Dan Murphy

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$line_break\
$jobs\
$character"""

[character]
success_symbol = "[\\$](bold green)"
error_symbol = "[\\$](bold red)"
vicmd_symbol = "[\\$](bold blue)"

[directory]
style = "bold blue"

[git_branch]
format = "on [$branch](bold purple)"

[git_status]
format = '([:](bold purple)[$all_status$ahead_behind](bold red))'
