# ~/.config/starship.toml
# Author: Dan Murphy

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$line_break\
$jobs\
$character"""

[character]
success_symbol = "[\\$](white)"
error_symbol = "[\\$](bold red)"
vicmd_symbol = "[\\$](bold blue)"

[git_branch]
format = "on [$branch]($style) "

[git_status]
deleted = "x"
