# Brewfile
# Author: Dan Murphy

# Development
brew 'bat'
brew 'gcc'
brew 'gdb'
brew 'git'
brew 'go'   # Needed by Vim package Hexokinase
brew 'htop'
brew 'macos-trash'
brew 'neovim'
brew 'python3'
brew 'sqlite'
brew 'starship'
brew 'stow'
brew 'tree'
brew 'zsh'
brew 'zsh-syntax-highlighting'

cask 'alacritty'
cask 'db-browser-for-sqlite'


# Fonts (including NERD Fonts)
tap 'homebrew/cask-fonts'

  # Standard Monospace Fonts
  brew 'font-cascadia-code'
  brew 'font-fantasque-sans-mono'
  #brew 'font-fantasque-sans-mono-noloopk'  # lowercase k without loop
  brew 'font-fira-code'
  brew 'font-hack'
  brew 'font-ibm-plex-mono'
  brew 'font-iosevka'
  brew 'font-jetbrains-mono'
  brew 'font-meslo-lg'
  #brew 'font-meslo-lg-dz'  # dotted zero
  brew 'font-roboto-mono'
  brew 'font-source-code-pro'

  # NERD Monospace Fonts
  brew 'font-blex-mono-nerd-font'
  brew 'font-fantasque-sans-mono-nerd-font'
  brew 'font-fira-code-nerd-font'
  brew 'font-hack-nerd-font'
  brew 'font-iosevka-nerd-font'
  brew 'font-meslo-lg-nerd-font'
  brew 'font-roboto-mono-nerd-font'
  brew 'font-sauce-code-pro-nerd-font'

  # Variable Fonts
  brew 'font-source-sans-pro'


# Other
brew 'ffmpeg'
brew 'youtube-dl'

