# By default, and in keeping with the
# [Style Guide](https://doc.rust-lang.org/beta/style-guide/expressions.html#single-line-if-else),
# rustfmt does not allow standalone `if else` statements on a single line.
# 
# To override this behaviour, you must set `version = "Two"` in your `rustfmt.toml` file and run
# rustfmt with the `+nightly` flag; see e.g.
# [this issue](https://github.com/rust-lang/rustfmt/issues/4351#issuecomment-663782224)
# for details.

version = "Two"
use_small_heuristics = "Max"
